-- Auto-loaded by LazyVim (on VeryLazy). LazyVim already provides
-- highlight-on-yank, auto-resize, last-cursor-position, etc.
--
-- Note: MautVim's project manager is registered in init.lua (early), not here,
-- because this file is deferred to VeryLazy — too late for its VimEnter hook.
